name: nodemarketcap
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.3
  share: ^0.5.2
  get_version: ^0.0.5
  sqflite: ^0.11.1
  http: ^0.11.3
  path_provider: ^0.4.1



dev_dependencies:
  flutter_test:
   sdk: flutter

flutter:
  uses-material-design: true
